### PR TITLE
Memescope custom beret

### PR DESCRIPTION
**Pull request by hey-it-stev**
Approved in https://forums.baystation12.net/threads/lichfield-agathus…-sasparov-asset-protection-medic-beret-memescope-mcgee.7089/#post-99492

### CODE REVIEW

**Comment by babydoll** [comment]
Made with an outdated fork, you have merge conflicts

**Comment by hey-it-stev** [comment]
Man I really can't figure out how the hell to make this work. I haven't done anything with github in like 8 months.

**Comment by babydoll** [comment]
@TheTrollDoctor you need to pull from the master branch and then re-do your changes, ask in coding if none of that makes sense

**Comment by babydoll** [comment]
Still has merge conflicts.

**Comment by babydoll** [comment]
Feel free to open a new PR with the fixes or find someone willing to do it for you.

**Pull request closed without merging**
