### PR TITLE
Adds tlc2013's Miko kimono, removes the old Caretaker's Dress.

### PR DESCRIPTION
**Pull request by tlc2013**
https://baystation12.net/forums/threads/miko-kimono-hikari-suzuki-tlc2013.6013/

Deletion request is also linked inside.

### CODE REVIEW

**Comment by PsiOmegaDelta** [comment]
You appear to have changed the newline format of custom_items.txt

**Comment by tlc2013** [comment]
...right. The fuck.

Give me about eight hours, I guess. Am currently about to go sleep.

**Comment by tlc2013** [comment]
I have a suspicion that the fix I just pushed didn't help at all. Mostly because the number of characters changed hasn't budged. The issue is, I don't even know what I did to begin with. I copy/pasted another person's entry and modified it to be for my own item because it'd be faster, and then _suddenly--_

**Comment by tlc2013** [comment]
_I DID IT HOLY SHIT._

I think most of that was just Sourcetree being a pain. But some of it's also on me. At least it's done with now.

It isn't too much of an issue if I slip the new entry in to replace the old one, is it? I hope it isn't, because that's how I got this to work.

**Comment by tlc2013** [comment]
...I suppose I should probably ping @PsiOmegaDelta for this, shouldn't I? Yeah, in hindsight, that would have been a good idea.

There we go, I guess.

**Pull request merged**
