### PR TITLE
Adds 5crownik007's Custom Item

### PR DESCRIPTION
**Pull request by 5crownik007**
please work this time

### CODE REVIEW

**Comment by PsiOmegaDelta** [comment]
Merge conflicts

**Comment by PsiOmegaDelta** [comment]
Still has merge conflicts.

**Comment by SubatomicTeddybear** [comment]
@5crownik007 The merge conflicts strike back!

**Comment by 5crownik007** [comment]
i'm not an expert
at first i thought your message "merge conflicts" meant that people should "merge the conflicts"
despite this i'll feex it ok

**Pull request closed without merging**
