### PR TITLE
adds TheGreyWolf's custom exoskeleton

### PR DESCRIPTION
**Pull request by Casper3667**
https://baystation12.net/forums/threads/exoskeleton-tasimi-thegreywolf.3707/

### CODE REVIEW

**Comment by Casper3667** [comment]
This must be a record merge for a custom item, nice.

**Comment by PsiOmegaDelta** [comment]
I'm currently compiling.

**Comment by Casper3667** [comment]
so the server is updating?

**Comment by PsiOmegaDelta** [comment]
Maybe, if someone else is doing that.
I'm compiling non-Bay code at this time.

**Comment by Casper3667** [comment]
alright, thanks for the merge anyway.

**Pull request merged**
