### PR TITLE
my super awesome locket thingy

### PR DESCRIPTION
**Pull request by Sabess**
I think
I think it's not broken
I hope

### CODE REVIEW

**Comment by GinjaNinja32** [comment]
Sprite appears to have a white background instead of a transparent one :(

**Comment by GinjaNinja32** [comment]
:+1:

edit: http://baystation12.net/archive/viewtopic.php?f=56&t=12564, for reference

**Comment by MistakeNot4892** [comment]
For the record, there is a locket item you could have based this on.

**Comment by GinjaNinja32** [comment]
...is there?

**Comment by MistakeNot4892** [comment]
```
/obj/item/clothing/accessory/locket
```

**Pull request merged**
