### PR TITLE
Fix issues with custom item mugs, c-i side

### PR DESCRIPTION
**Pull request by babydoll**
See https://github.com/Baystation12/Baystation12/pull/27775 for details

### CODE REVIEW

**Comment by afterthought2** [comment]
Isn't there one or two other mugs?

**Comment by babydoll** [comment]
This is the only one remaining

**Comment by babydoll** [comment]
~~This is also a WIP, waiting for the new icon that fits the liquid overlay~~

**Comment by babydoll** [comment]
conflicts resolved

**Review by afterthought2 — APPROVED** [review]

**Pull request merged**
