### PR TITLE
Styx 8* - Custom Synthetic sprite - ParadoxSpace

### PR DESCRIPTION
**Pull request by MrSnapwalk**
http://baystation12.net/forums/threads/custom-synth-sprite-styx-8-paradoxspace.144/

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
You need to also add an entry to the config.

**Comment by MrSnapwalk** [comment]
I asked about that in #codershuttle and on the forums, and no one gave me a straight answer - give me two seconds.

**Comment by MistakeNot4892** [comment]
https://github.com/Baystation12/custom-items/blob/master/config/custom_sprites.txt

**Comment by MrSnapwalk** [comment]
Yep, I know. However, there are literally no config entries in there (even for the pre-existing synthetics that were imported from the main repo), so I didn't know if custom synthetic sprites were being handled here or on the server itself.

**Comment by MistakeNot4892** [comment]
It would not be in the repo if it wasn't intended to be handled here.

**Comment by MrSnapwalk** [comment]
Done, now we know.

**Comment by mwerezak** [comment]
EDIT: My mistake, didn't know how custom cyborg icons worked, and just looked it up. Looks fine.

**Comment by ParadoxSpace** [comment]
It's important to the name, much like Acheron 7*

**Comment by mwerezak** [comment]
Yeah, it's fine. The header at the top of the file is misleading, it should read `ckey-charactername`.

**Comment by Nerev4r** [comment]
That should probably be fixed somewhere along the line tbh.

**Comment by MistakeNot4892** [comment]
The character name IS the state.

**Pull request merged**
