### PR TITLE
Removes tlc2013's Old Switchblade, replaces it with a Custom AI Core

### PR DESCRIPTION
**Pull request by tlc2013**
The core's approval thread:
https://baystation12.net/forums/threads/custom-a-i-mainframe-g-l-a-i-v-e-tlc2013.4839/

Aaand just in case you feel like asking, the removal thread:
https://baystation12.net/forums/threads/approved-deletion-request-old-switchblade-charlotte-kieran.4829/

Here's hoping I didn't screw anything up this time.

### CODE REVIEW

**Comment by tlc2013** [comment]
Aaaand the conflict thing's happening again. Right, I think I have a vague idea as to _why_ it's happening this time around, and I _miiiight_ know how to avoid it next time (if there is a next time) but I haven't the slightest idea how to fix it without blindly stumbling around in Git, so... I'm going to need a little help there, I guess.

**Comment by PsiOmegaDelta** [comment]
It's happening because you're not basing your branch of the latest commit.

**Comment by tlc2013** [comment]
Thanks for confirming my suspicions. While that lets me know how to avoid running into this sort of problem again, which is going to be massively helpful later, it doesn't really help me with fixing it _this time._ So, er... yeah. Sorry for the inconvenience, but I'll probably need you to fix that for me.

**Comment by tlc2013** [comment]
Aaand it's happening even more, because I wanted to account for that tape recorder... damn. Uh, yeah, I cleared up the issue with the files being outdated (what with the tape recorder PR getting merged and all), but now it's got a second conflict going on. And probably needs a squash. And I'm terrible with Git, so I can't fix either of those myself.

Man, I'm kind of terrible at this. Uh... yeah. Still. Help?

**Comment by PsiOmegaDelta** [comment]
Fetch.
Checkout latest commit as a new branch.

Dunno how to do that in the web client or Github Desktop. In most actual git clients it should be straight forward.

**Comment by tlc2013** [comment]
So I went into Git, with the help of Nyvrem, and I actually managed to figure out how to use the interface. Vaguely.

I still couldn't fix the conflicts, for reasons that I can't tell you properly because I just closed the console.

As my minor meltdown in the coding channel probably demonstrated, I'm currently too frustrated to do anything with Git at all, so, er... @PsiOmegaDelta, if you (or someone else with access) could go in and fix these bloody conflicts for me, that would be highly appreciated. I'll learn how to do this stuff later, in a situation where failure doesn't make my blood boil.

Thanks for the pointers, though. You _did_ give me a good idea of where to look for figuring this out; I just couldn't work with it. The whole "eight days of nothing" thing probably had me a little over-eager to just finally get this mess fixed, I suppose, and... well. I got frustrated.

Me and consoles just don't seem to mix well.

**Comment by Casper3667** [comment]
the contents of this PR is handled over in https://github.com/Baystation12/custom-items/pull/129 since I thought it would be helpful.

**Comment by tlc2013** [comment]
@Casper3667 Yep. Thanks! I'll close this now, considering it's been more-or-less handled.

**Pull request closed without merging**
