### PR TITLE
Adds tlc2013's Caretaker's Dress.

### PR DESCRIPTION
**Pull request by tlc2013**
The application (directly linking to the "approved" post) can be found here:
https://baystation12.net/forums/threads/caretakers-dress-kyra-tlc2013.4760/#post-70438

(as a side note, ignore that first commit; I can't figure out how to squash commits to save my life, and it changes nothing. Was just updating my fork.)

### CODE REVIEW

**Comment by PsiOmegaDelta** [comment]
Merge conflicts.

**Comment by tlc2013** [comment]
I should have probably accounted for that to begin with. Heh. Anyway, should be fixed now, I think?

**Comment by PsiOmegaDelta** [comment]
Still has merge conflicts. I see no merge commits that would've resolved it.

**Comment by tlc2013** [comment]
@PsiOmegaDelta ...huh. I updated the files to account for the item removal PR that you merged last night... what else could I possibly have missed?

**Comment by PsiOmegaDelta** [comment]
You haven't merged with the main branch, it's basically a separated command from a general commit.
The PR will be in conflict until you do.

**Comment by tlc2013** [comment]
@PsiOmegaDelta I'm not on Git, to be clear; the console physically pains me to use. So... yeah. Even if I was, though, I can't find anything about that on Google, so I'm rather confused. Help, I guess?

**Comment by tlc2013** [comment]
@PsiOmegaDelta Okay, I wound up having to ask Snapshot for help, but I got it fixed. So... yeah! You can merge this now, I think.

**Pull request merged**
