### PR TITLE
fix mistake with the resistance coat

### PR DESCRIPTION
**Pull request by Casper3667**
i forgot to make it able to be opened and closed... this should hopefully fix it.

### CODE REVIEW

**Comment by Casper3667** [comment]
i don't even... anyone able to tell me why it is failing so i can try to fix it?

**Comment by martinlyra** [comment]
`558: Unknown key: icon_open
559: Unknown key: icon_closed`

Looking in the script, those keys are not included. You are not the one to be blamed. Up to the developers if they want to add those keys as recognized keys or not.

**Comment by Casper3667** [comment]
great, nothing i can do then beside adjusting to at least start with the closed version

**Comment by GinjaNinja32** [comment]
IIRC togglable clothing is specified by closed state, and open state is simply `"[base_icon_state]_open"`

**Pull request merged**
