### PR TITLE
Removes danny220's custom AI sprite, as requested

### PR DESCRIPTION
**Pull request by babydoll**

### CODE REVIEW

**Comment by PsiOmegaDelta** [comment]
@Raptor

**Comment by PsiOmegaDelta** [comment]
Will contact staff to discern the exact policy concerning the removal of icons, relating to paper/forum trails.

**Comment by babydoll** [comment]
I've let him know he needs to make a deletion request before this goes further.

**Comment by babydoll** [comment]
https://baystation12.net/forums/threads/deletion-request-danny220-custom-ai-sprite.3672/

**Comment by babydoll** [comment]
@PsiOmegaDelta Bump?

**Pull request merged**
