### PR TITLE
PWCD| Plaugewalker Custom Item

### PR DESCRIPTION
**Pull request by Plaguewalker**
I have had this approved by Eckles: https://forums.baystation12.net/threads/pwcd-elias-ganning-plaugewalker.8189/| Gotta love doing it the hard way

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
Please stop opening a new PR every time, you only need to push to the same branch to update one.

**Comment by Plaguewalker** [comment]
Right, well this was the last time  I hope there shouldn't be a hang up

**Comment by afterthought2** [comment]
Please make them non-think and possibly non-duty, depending on the jobs they are available to. `thick` confers some minor mechanical advantages and should not be given to roles that can't otherwise obtain them from loadout or outfit (such as Passenger and Crewman). I'm not sure what `duty` does other than an overridden sprite change, so probably not needed.

**Comment by Plaguewalker** [comment]
Okay, did a fresh update using bog standard gloves with no special attributes.

**Comment by Plaguewalker** [comment]
Squashed

**Pull request merged**
