### PR TITLE
Added Annie

### PR DESCRIPTION
**Pull request by Decepteor**

### CODE REVIEW

**Comment by babydoll** [comment]
The `miner` eyes state is named inconsistently, which will cause problems. It has capital letters

**Comment by babydoll** [comment]
And merge conflicts

**Comment by Decepteor** [comment]
I updated this, it should now be better

**Comment by PsiOmegaDelta** [comment]
Link to approval thread?

**Comment by GracieGrace0** [comment]
https://forums.baystation12.net/threads/annie-cyborg-graciegrace0.6888/

**Comment by babydoll** [comment]
Still has merge conflicts, as well

**Comment by GracieGrace0** [comment]
@PsiOmegaDelta  @sabiram  Its fixed again. Please save us.

**Pull request merged**
