### PR TITLE
Leslie Souhan's Spacer Jumpsuit and this time I figured out github

### PR DESCRIPTION
**Pull request by 5crownik007**
Everything is in order this time

### CODE REVIEW

**Comment by PsiOmegaDelta** [comment]
Multiple conflicts.

**Comment by Kearel** [comment]
Still conflicts. You'll need to merge the current version of the repo.

**Comment by PsiOmegaDelta** [comment]
Closing due to being stale.

**Comment by 5crownik007** [comment]
shoot damnit
can someone actually explain this to me i'm an idiot alright

**Comment by PsiOmegaDelta** [comment]
Easiest might be if you join either Discord or IRC, whichever you prefer and talk with us there:

Discord: https://discord.gg/DrtRFxs
Channel: #coding

IRC: http://webchat.sorcery.net/?channels=#bs12 or #bs12 on irc.sorcery.net
Channel: #codershuttle

**Comment by PsiOmegaDelta** [comment]
Easiest might be if you join either Discord or IRC, whichever you prefer and talk with us there:

Discord: https://discord.gg/DrtRFxs
Channel: #coding

IRC: http://webchat.sorcery.net/?channels=#codershuttle or #codershuttle on irc.sorcery.net

**Pull request closed without merging**
